version: '3.8'

services:
  backend:
    build: .
    container_name: csts_app
    command: |
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py initialize_admin_user &&
        python manage.py runserver 0.0.0.0:${BACKEND_PORT}
      "
    volumes:
      - .:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # POSTGRES_DB: postgres
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  postgres_data:
