# Generated by Django 5.1.7 on 2025-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('ticketTitle', models.CharField(max_length=255)),
                ('ticketDescription', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resloved', 'Resolved')], max_length=20)),
                ('senderName', models.CharField(max_length=30)),
                ('senderEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
